Fix typo in README.md
plotters-rs/plotters pull request #160
Opened 2020-07-11 09:05 UTC by legoktm

2020-09-09 22:39 UTC, 38 requested changes

2020-09-09 22:39 UTC, 38 commented on README.md
> -| datetime | Eanble the date and time coordinate support | chrono | Yes |
This readme is automatically generated with doc-template/readme.template.md. If you don't mind could you please change it there and run the doc-template/update-readme.sh please. Thanks!

2021-06-30 09:26 UTC, LollipopFt commented
there's a typo in readme:

- How to check if a backend writes file successfully ?

The behavior of Plotters backend is consistent with stadnard library...

2024-04-13 22:35 UTC, jayvdb commented
Hey @legoktm , this PR is really old.  Probably best to just drop it.

2024-05-03 06:19 UTC, jayvdb commented
And likely already fixed by https://github.com/plotters-rs/plotters/pull/570

2024-05-03 21:31 UTC, legoktm commented
> And likely already fixed by #570

Hey, good to see you around :) Awesome, I had totally forgotten about this.

2024-05-03 21:31 UTC, closed without merging